version: "3.8"

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/boilerplate-authen-api
    volumes:
      - ./be:/app
    restart: unless-stopped

  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    restart: unless-stopped

volumes:
  mongo_data:
